-- AUTO-GENERATED by codegen/gen-ast.js — DO NOT EDIT
-- FromJSON instance lives in AST.Types to avoid circular dependency.
-- This module is kept for backward compatibility.
module AST.Decode (module AST.Types) where

import AST.Types
