{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE StrictData #-}
-- AUTO-GENERATED by codegen/gen-ast.js — DO NOT EDIT
module AST.Span
  ( Span(..)
  , SourceLoc(..)
  , byteOffsetToLoc
  , buildLineIndex
  ) where

import GHC.Generics (Generic)
import qualified Data.ByteString as BS
import Data.Word (Word8)

-- | Byte-offset span from OXC parser.
data Span = Span
  { spanStart :: !Int
  , spanEnd   :: !Int
  } deriving (Show, Eq, Generic)

-- | 1-based line, 0-based column.
data SourceLoc = SourceLoc
  { locLine   :: !Int  -- ^ 1-based
  , locColumn :: !Int  -- ^ 0-based
  } deriving (Show, Eq)

-- | Precomputed index: byte offset of each line start.
-- Index ! 0 = 0 (line 1 starts at byte 0).
type LineIndex = [Int]

-- | Scan source bytes for newline positions. O(n) in source length.
buildLineIndex :: BS.ByteString -> LineIndex
buildLineIndex src = 0 : go 0 (BS.unpack src)
  where
    nl :: Word8
    nl = 0x0A  -- '\n'
    go _ []     = []
    go i (b:bs)
      | b == nl   = (i + 1) : go (i + 1) bs
      | otherwise  = go (i + 1) bs

-- | Convert a byte offset to line:column using a precomputed LineIndex.
-- Binary search for the line, then column = offset - lineStart.
byteOffsetToLoc :: LineIndex -> Int -> SourceLoc
byteOffsetToLoc idx offset = go 1 idx
  where
    go lineNum []     = SourceLoc lineNum offset
    go lineNum [s]    = SourceLoc lineNum (offset - s)
    go lineNum (s:rest@(next:_))
      | offset < next = SourceLoc lineNum (offset - s)
      | otherwise     = go (lineNum + 1) rest
