{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StrictData #-}
-- AUTO-GENERATED by codegen/gen-ast.js — DO NOT EDIT
-- Source: @oxc-project/types@0.96.0
module AST.Types
  ( ASTNode(..)
  , astNodeType
  , astNodeSpan
  , astNodeFields
  , getField
  , getFieldMaybe
  , getChildren
  , getChildrenMaybe
  , getTextFieldOr
  , getBoolFieldOr
  ) where

import Data.Aeson (FromJSON(..), Value(..), Object, withObject, (.:))
import Data.Aeson.Types (Parser, parseMaybe)
import Data.Text (Text)
import qualified Data.Aeson.KeyMap as KM
import qualified Data.Aeson.Key as K
import qualified Data.Vector as V
import AST.Span (Span(..))

-- | One constructor per ESTree node type (166 total).
-- Each carries the byte-offset Span and the raw JSON Object for field access.
data ASTNode
    = AccessorPropertyNode !Span !Object
    | ArrayExpressionNode !Span !Object
    | ArrayPatternNode !Span !Object
    | ArrowFunctionExpressionNode !Span !Object
    | AssignmentExpressionNode !Span !Object
    | AssignmentPatternNode !Span !Object
    | AwaitExpressionNode !Span !Object
    | BinaryExpressionNode !Span !Object
    | BlockStatementNode !Span !Object
    | BreakStatementNode !Span !Object
    | CallExpressionNode !Span !Object
    | CatchClauseNode !Span !Object
    | ChainExpressionNode !Span !Object
    | ClassBodyNode !Span !Object
    | ClassDeclarationNode !Span !Object
    | ClassExpressionNode !Span !Object
    | ConditionalExpressionNode !Span !Object
    | ContinueStatementNode !Span !Object
    | DebuggerStatementNode !Span !Object
    | DecoratorNode !Span !Object
    | DoWhileStatementNode !Span !Object
    | EmptyStatementNode !Span !Object
    | ExportAllDeclarationNode !Span !Object
    | ExportDefaultDeclarationNode !Span !Object
    | ExportNamedDeclarationNode !Span !Object
    | ExportSpecifierNode !Span !Object
    | ExpressionStatementNode !Span !Object
    | ForInStatementNode !Span !Object
    | ForOfStatementNode !Span !Object
    | ForStatementNode !Span !Object
    | FunctionDeclarationNode !Span !Object
    | FunctionExpressionNode !Span !Object
    | HashbangNode !Span !Object
    | IdentifierNode !Span !Object
    | IfStatementNode !Span !Object
    | ImportAttributeNode !Span !Object
    | ImportDeclarationNode !Span !Object
    | ImportDefaultSpecifierNode !Span !Object
    | ImportExpressionNode !Span !Object
    | ImportNamespaceSpecifierNode !Span !Object
    | ImportSpecifierNode !Span !Object
    | JSXAttributeNode !Span !Object
    | JSXClosingElementNode !Span !Object
    | JSXClosingFragmentNode !Span !Object
    | JSXElementNode !Span !Object
    | JSXEmptyExpressionNode !Span !Object
    | JSXExpressionContainerNode !Span !Object
    | JSXFragmentNode !Span !Object
    | JSXIdentifierNode !Span !Object
    | JSXMemberExpressionNode !Span !Object
    | JSXNamespacedNameNode !Span !Object
    | JSXOpeningElementNode !Span !Object
    | JSXOpeningFragmentNode !Span !Object
    | JSXSpreadAttributeNode !Span !Object
    | JSXSpreadChildNode !Span !Object
    | JSXTextNode !Span !Object
    | LabeledStatementNode !Span !Object
    | LiteralNode !Span !Object
    | LogicalExpressionNode !Span !Object
    | MemberExpressionNode !Span !Object
    | MetaPropertyNode !Span !Object
    | MethodDefinitionNode !Span !Object
    | NewExpressionNode !Span !Object
    | ObjectExpressionNode !Span !Object
    | ObjectPatternNode !Span !Object
    | ParenthesizedExpressionNode !Span !Object
    | PrivateIdentifierNode !Span !Object
    | ProgramNode !Span !Object
    | PropertyNode !Span !Object
    | PropertyDefinitionNode !Span !Object
    | RestElementNode !Span !Object
    | ReturnStatementNode !Span !Object
    | SequenceExpressionNode !Span !Object
    | SpreadElementNode !Span !Object
    | StaticBlockNode !Span !Object
    | SuperNode !Span !Object
    | SwitchCaseNode !Span !Object
    | SwitchStatementNode !Span !Object
    | TSAbstractAccessorPropertyNode !Span !Object
    | TSAbstractMethodDefinitionNode !Span !Object
    | TSAbstractPropertyDefinitionNode !Span !Object
    | TSAnyKeywordNode !Span !Object
    | TSArrayTypeNode !Span !Object
    | TSAsExpressionNode !Span !Object
    | TSBigIntKeywordNode !Span !Object
    | TSBooleanKeywordNode !Span !Object
    | TSCallSignatureDeclarationNode !Span !Object
    | TSClassImplementsNode !Span !Object
    | TSConditionalTypeNode !Span !Object
    | TSConstructSignatureDeclarationNode !Span !Object
    | TSConstructorTypeNode !Span !Object
    | TSDeclareFunctionNode !Span !Object
    | TSEmptyBodyFunctionExpressionNode !Span !Object
    | TSEnumBodyNode !Span !Object
    | TSEnumDeclarationNode !Span !Object
    | TSEnumMemberNode !Span !Object
    | TSExportAssignmentNode !Span !Object
    | TSExternalModuleReferenceNode !Span !Object
    | TSFunctionTypeNode !Span !Object
    | TSImportEqualsDeclarationNode !Span !Object
    | TSImportTypeNode !Span !Object
    | TSIndexSignatureNode !Span !Object
    | TSIndexedAccessTypeNode !Span !Object
    | TSInferTypeNode !Span !Object
    | TSInstantiationExpressionNode !Span !Object
    | TSInterfaceBodyNode !Span !Object
    | TSInterfaceDeclarationNode !Span !Object
    | TSInterfaceHeritageNode !Span !Object
    | TSIntersectionTypeNode !Span !Object
    | TSIntrinsicKeywordNode !Span !Object
    | TSJSDocNonNullableTypeNode !Span !Object
    | TSJSDocNullableTypeNode !Span !Object
    | TSJSDocUnknownTypeNode !Span !Object
    | TSLiteralTypeNode !Span !Object
    | TSMappedTypeNode !Span !Object
    | TSMethodSignatureNode !Span !Object
    | TSModuleBlockNode !Span !Object
    | TSModuleDeclarationNode !Span !Object
    | TSNamedTupleMemberNode !Span !Object
    | TSNamespaceExportDeclarationNode !Span !Object
    | TSNeverKeywordNode !Span !Object
    | TSNonNullExpressionNode !Span !Object
    | TSNullKeywordNode !Span !Object
    | TSNumberKeywordNode !Span !Object
    | TSObjectKeywordNode !Span !Object
    | TSOptionalTypeNode !Span !Object
    | TSParameterPropertyNode !Span !Object
    | TSParenthesizedTypeNode !Span !Object
    | TSPropertySignatureNode !Span !Object
    | TSQualifiedNameNode !Span !Object
    | TSRestTypeNode !Span !Object
    | TSSatisfiesExpressionNode !Span !Object
    | TSStringKeywordNode !Span !Object
    | TSSymbolKeywordNode !Span !Object
    | TSTemplateLiteralTypeNode !Span !Object
    | TSThisTypeNode !Span !Object
    | TSTupleTypeNode !Span !Object
    | TSTypeAliasDeclarationNode !Span !Object
    | TSTypeAnnotationNode !Span !Object
    | TSTypeAssertionNode !Span !Object
    | TSTypeLiteralNode !Span !Object
    | TSTypeOperatorNode !Span !Object
    | TSTypeParameterNode !Span !Object
    | TSTypeParameterDeclarationNode !Span !Object
    | TSTypeParameterInstantiationNode !Span !Object
    | TSTypePredicateNode !Span !Object
    | TSTypeQueryNode !Span !Object
    | TSTypeReferenceNode !Span !Object
    | TSUndefinedKeywordNode !Span !Object
    | TSUnionTypeNode !Span !Object
    | TSUnknownKeywordNode !Span !Object
    | TSVoidKeywordNode !Span !Object
    | TaggedTemplateExpressionNode !Span !Object
    | TemplateElementNode !Span !Object
    | TemplateLiteralNode !Span !Object
    | ThisExpressionNode !Span !Object
    | ThrowStatementNode !Span !Object
    | TryStatementNode !Span !Object
    | UnaryExpressionNode !Span !Object
    | UpdateExpressionNode !Span !Object
    | V8IntrinsicExpressionNode !Span !Object
    | VariableDeclarationNode !Span !Object
    | VariableDeclaratorNode !Span !Object
    | WhileStatementNode !Span !Object
    | WithStatementNode !Span !Object
    | YieldExpressionNode !Span !Object
    | UnknownNode !Text !Span !Object   -- ^ Fallback for unrecognized types
    deriving (Show)

-- | Extract the ESTree type string from a node.
astNodeType :: ASTNode -> Text
astNodeType (AccessorPropertyNode _ _) = "AccessorProperty"
astNodeType (ArrayExpressionNode _ _) = "ArrayExpression"
astNodeType (ArrayPatternNode _ _) = "ArrayPattern"
astNodeType (ArrowFunctionExpressionNode _ _) = "ArrowFunctionExpression"
astNodeType (AssignmentExpressionNode _ _) = "AssignmentExpression"
astNodeType (AssignmentPatternNode _ _) = "AssignmentPattern"
astNodeType (AwaitExpressionNode _ _) = "AwaitExpression"
astNodeType (BinaryExpressionNode _ _) = "BinaryExpression"
astNodeType (BlockStatementNode _ _) = "BlockStatement"
astNodeType (BreakStatementNode _ _) = "BreakStatement"
astNodeType (CallExpressionNode _ _) = "CallExpression"
astNodeType (CatchClauseNode _ _) = "CatchClause"
astNodeType (ChainExpressionNode _ _) = "ChainExpression"
astNodeType (ClassBodyNode _ _) = "ClassBody"
astNodeType (ClassDeclarationNode _ _) = "ClassDeclaration"
astNodeType (ClassExpressionNode _ _) = "ClassExpression"
astNodeType (ConditionalExpressionNode _ _) = "ConditionalExpression"
astNodeType (ContinueStatementNode _ _) = "ContinueStatement"
astNodeType (DebuggerStatementNode _ _) = "DebuggerStatement"
astNodeType (DecoratorNode _ _) = "Decorator"
astNodeType (DoWhileStatementNode _ _) = "DoWhileStatement"
astNodeType (EmptyStatementNode _ _) = "EmptyStatement"
astNodeType (ExportAllDeclarationNode _ _) = "ExportAllDeclaration"
astNodeType (ExportDefaultDeclarationNode _ _) = "ExportDefaultDeclaration"
astNodeType (ExportNamedDeclarationNode _ _) = "ExportNamedDeclaration"
astNodeType (ExportSpecifierNode _ _) = "ExportSpecifier"
astNodeType (ExpressionStatementNode _ _) = "ExpressionStatement"
astNodeType (ForInStatementNode _ _) = "ForInStatement"
astNodeType (ForOfStatementNode _ _) = "ForOfStatement"
astNodeType (ForStatementNode _ _) = "ForStatement"
astNodeType (FunctionDeclarationNode _ _) = "FunctionDeclaration"
astNodeType (FunctionExpressionNode _ _) = "FunctionExpression"
astNodeType (HashbangNode _ _) = "Hashbang"
astNodeType (IdentifierNode _ _) = "Identifier"
astNodeType (IfStatementNode _ _) = "IfStatement"
astNodeType (ImportAttributeNode _ _) = "ImportAttribute"
astNodeType (ImportDeclarationNode _ _) = "ImportDeclaration"
astNodeType (ImportDefaultSpecifierNode _ _) = "ImportDefaultSpecifier"
astNodeType (ImportExpressionNode _ _) = "ImportExpression"
astNodeType (ImportNamespaceSpecifierNode _ _) = "ImportNamespaceSpecifier"
astNodeType (ImportSpecifierNode _ _) = "ImportSpecifier"
astNodeType (JSXAttributeNode _ _) = "JSXAttribute"
astNodeType (JSXClosingElementNode _ _) = "JSXClosingElement"
astNodeType (JSXClosingFragmentNode _ _) = "JSXClosingFragment"
astNodeType (JSXElementNode _ _) = "JSXElement"
astNodeType (JSXEmptyExpressionNode _ _) = "JSXEmptyExpression"
astNodeType (JSXExpressionContainerNode _ _) = "JSXExpressionContainer"
astNodeType (JSXFragmentNode _ _) = "JSXFragment"
astNodeType (JSXIdentifierNode _ _) = "JSXIdentifier"
astNodeType (JSXMemberExpressionNode _ _) = "JSXMemberExpression"
astNodeType (JSXNamespacedNameNode _ _) = "JSXNamespacedName"
astNodeType (JSXOpeningElementNode _ _) = "JSXOpeningElement"
astNodeType (JSXOpeningFragmentNode _ _) = "JSXOpeningFragment"
astNodeType (JSXSpreadAttributeNode _ _) = "JSXSpreadAttribute"
astNodeType (JSXSpreadChildNode _ _) = "JSXSpreadChild"
astNodeType (JSXTextNode _ _) = "JSXText"
astNodeType (LabeledStatementNode _ _) = "LabeledStatement"
astNodeType (LiteralNode _ _) = "Literal"
astNodeType (LogicalExpressionNode _ _) = "LogicalExpression"
astNodeType (MemberExpressionNode _ _) = "MemberExpression"
astNodeType (MetaPropertyNode _ _) = "MetaProperty"
astNodeType (MethodDefinitionNode _ _) = "MethodDefinition"
astNodeType (NewExpressionNode _ _) = "NewExpression"
astNodeType (ObjectExpressionNode _ _) = "ObjectExpression"
astNodeType (ObjectPatternNode _ _) = "ObjectPattern"
astNodeType (ParenthesizedExpressionNode _ _) = "ParenthesizedExpression"
astNodeType (PrivateIdentifierNode _ _) = "PrivateIdentifier"
astNodeType (ProgramNode _ _) = "Program"
astNodeType (PropertyNode _ _) = "Property"
astNodeType (PropertyDefinitionNode _ _) = "PropertyDefinition"
astNodeType (RestElementNode _ _) = "RestElement"
astNodeType (ReturnStatementNode _ _) = "ReturnStatement"
astNodeType (SequenceExpressionNode _ _) = "SequenceExpression"
astNodeType (SpreadElementNode _ _) = "SpreadElement"
astNodeType (StaticBlockNode _ _) = "StaticBlock"
astNodeType (SuperNode _ _) = "Super"
astNodeType (SwitchCaseNode _ _) = "SwitchCase"
astNodeType (SwitchStatementNode _ _) = "SwitchStatement"
astNodeType (TSAbstractAccessorPropertyNode _ _) = "TSAbstractAccessorProperty"
astNodeType (TSAbstractMethodDefinitionNode _ _) = "TSAbstractMethodDefinition"
astNodeType (TSAbstractPropertyDefinitionNode _ _) = "TSAbstractPropertyDefinition"
astNodeType (TSAnyKeywordNode _ _) = "TSAnyKeyword"
astNodeType (TSArrayTypeNode _ _) = "TSArrayType"
astNodeType (TSAsExpressionNode _ _) = "TSAsExpression"
astNodeType (TSBigIntKeywordNode _ _) = "TSBigIntKeyword"
astNodeType (TSBooleanKeywordNode _ _) = "TSBooleanKeyword"
astNodeType (TSCallSignatureDeclarationNode _ _) = "TSCallSignatureDeclaration"
astNodeType (TSClassImplementsNode _ _) = "TSClassImplements"
astNodeType (TSConditionalTypeNode _ _) = "TSConditionalType"
astNodeType (TSConstructSignatureDeclarationNode _ _) = "TSConstructSignatureDeclaration"
astNodeType (TSConstructorTypeNode _ _) = "TSConstructorType"
astNodeType (TSDeclareFunctionNode _ _) = "TSDeclareFunction"
astNodeType (TSEmptyBodyFunctionExpressionNode _ _) = "TSEmptyBodyFunctionExpression"
astNodeType (TSEnumBodyNode _ _) = "TSEnumBody"
astNodeType (TSEnumDeclarationNode _ _) = "TSEnumDeclaration"
astNodeType (TSEnumMemberNode _ _) = "TSEnumMember"
astNodeType (TSExportAssignmentNode _ _) = "TSExportAssignment"
astNodeType (TSExternalModuleReferenceNode _ _) = "TSExternalModuleReference"
astNodeType (TSFunctionTypeNode _ _) = "TSFunctionType"
astNodeType (TSImportEqualsDeclarationNode _ _) = "TSImportEqualsDeclaration"
astNodeType (TSImportTypeNode _ _) = "TSImportType"
astNodeType (TSIndexSignatureNode _ _) = "TSIndexSignature"
astNodeType (TSIndexedAccessTypeNode _ _) = "TSIndexedAccessType"
astNodeType (TSInferTypeNode _ _) = "TSInferType"
astNodeType (TSInstantiationExpressionNode _ _) = "TSInstantiationExpression"
astNodeType (TSInterfaceBodyNode _ _) = "TSInterfaceBody"
astNodeType (TSInterfaceDeclarationNode _ _) = "TSInterfaceDeclaration"
astNodeType (TSInterfaceHeritageNode _ _) = "TSInterfaceHeritage"
astNodeType (TSIntersectionTypeNode _ _) = "TSIntersectionType"
astNodeType (TSIntrinsicKeywordNode _ _) = "TSIntrinsicKeyword"
astNodeType (TSJSDocNonNullableTypeNode _ _) = "TSJSDocNonNullableType"
astNodeType (TSJSDocNullableTypeNode _ _) = "TSJSDocNullableType"
astNodeType (TSJSDocUnknownTypeNode _ _) = "TSJSDocUnknownType"
astNodeType (TSLiteralTypeNode _ _) = "TSLiteralType"
astNodeType (TSMappedTypeNode _ _) = "TSMappedType"
astNodeType (TSMethodSignatureNode _ _) = "TSMethodSignature"
astNodeType (TSModuleBlockNode _ _) = "TSModuleBlock"
astNodeType (TSModuleDeclarationNode _ _) = "TSModuleDeclaration"
astNodeType (TSNamedTupleMemberNode _ _) = "TSNamedTupleMember"
astNodeType (TSNamespaceExportDeclarationNode _ _) = "TSNamespaceExportDeclaration"
astNodeType (TSNeverKeywordNode _ _) = "TSNeverKeyword"
astNodeType (TSNonNullExpressionNode _ _) = "TSNonNullExpression"
astNodeType (TSNullKeywordNode _ _) = "TSNullKeyword"
astNodeType (TSNumberKeywordNode _ _) = "TSNumberKeyword"
astNodeType (TSObjectKeywordNode _ _) = "TSObjectKeyword"
astNodeType (TSOptionalTypeNode _ _) = "TSOptionalType"
astNodeType (TSParameterPropertyNode _ _) = "TSParameterProperty"
astNodeType (TSParenthesizedTypeNode _ _) = "TSParenthesizedType"
astNodeType (TSPropertySignatureNode _ _) = "TSPropertySignature"
astNodeType (TSQualifiedNameNode _ _) = "TSQualifiedName"
astNodeType (TSRestTypeNode _ _) = "TSRestType"
astNodeType (TSSatisfiesExpressionNode _ _) = "TSSatisfiesExpression"
astNodeType (TSStringKeywordNode _ _) = "TSStringKeyword"
astNodeType (TSSymbolKeywordNode _ _) = "TSSymbolKeyword"
astNodeType (TSTemplateLiteralTypeNode _ _) = "TSTemplateLiteralType"
astNodeType (TSThisTypeNode _ _) = "TSThisType"
astNodeType (TSTupleTypeNode _ _) = "TSTupleType"
astNodeType (TSTypeAliasDeclarationNode _ _) = "TSTypeAliasDeclaration"
astNodeType (TSTypeAnnotationNode _ _) = "TSTypeAnnotation"
astNodeType (TSTypeAssertionNode _ _) = "TSTypeAssertion"
astNodeType (TSTypeLiteralNode _ _) = "TSTypeLiteral"
astNodeType (TSTypeOperatorNode _ _) = "TSTypeOperator"
astNodeType (TSTypeParameterNode _ _) = "TSTypeParameter"
astNodeType (TSTypeParameterDeclarationNode _ _) = "TSTypeParameterDeclaration"
astNodeType (TSTypeParameterInstantiationNode _ _) = "TSTypeParameterInstantiation"
astNodeType (TSTypePredicateNode _ _) = "TSTypePredicate"
astNodeType (TSTypeQueryNode _ _) = "TSTypeQuery"
astNodeType (TSTypeReferenceNode _ _) = "TSTypeReference"
astNodeType (TSUndefinedKeywordNode _ _) = "TSUndefinedKeyword"
astNodeType (TSUnionTypeNode _ _) = "TSUnionType"
astNodeType (TSUnknownKeywordNode _ _) = "TSUnknownKeyword"
astNodeType (TSVoidKeywordNode _ _) = "TSVoidKeyword"
astNodeType (TaggedTemplateExpressionNode _ _) = "TaggedTemplateExpression"
astNodeType (TemplateElementNode _ _) = "TemplateElement"
astNodeType (TemplateLiteralNode _ _) = "TemplateLiteral"
astNodeType (ThisExpressionNode _ _) = "ThisExpression"
astNodeType (ThrowStatementNode _ _) = "ThrowStatement"
astNodeType (TryStatementNode _ _) = "TryStatement"
astNodeType (UnaryExpressionNode _ _) = "UnaryExpression"
astNodeType (UpdateExpressionNode _ _) = "UpdateExpression"
astNodeType (V8IntrinsicExpressionNode _ _) = "V8IntrinsicExpression"
astNodeType (VariableDeclarationNode _ _) = "VariableDeclaration"
astNodeType (VariableDeclaratorNode _ _) = "VariableDeclarator"
astNodeType (WhileStatementNode _ _) = "WhileStatement"
astNodeType (WithStatementNode _ _) = "WithStatement"
astNodeType (YieldExpressionNode _ _) = "YieldExpression"
astNodeType (UnknownNode t _ _) = t

-- | Extract the Span from a node.
astNodeSpan :: ASTNode -> Span
astNodeSpan (AccessorPropertyNode s _) = s
astNodeSpan (ArrayExpressionNode s _) = s
astNodeSpan (ArrayPatternNode s _) = s
astNodeSpan (ArrowFunctionExpressionNode s _) = s
astNodeSpan (AssignmentExpressionNode s _) = s
astNodeSpan (AssignmentPatternNode s _) = s
astNodeSpan (AwaitExpressionNode s _) = s
astNodeSpan (BinaryExpressionNode s _) = s
astNodeSpan (BlockStatementNode s _) = s
astNodeSpan (BreakStatementNode s _) = s
astNodeSpan (CallExpressionNode s _) = s
astNodeSpan (CatchClauseNode s _) = s
astNodeSpan (ChainExpressionNode s _) = s
astNodeSpan (ClassBodyNode s _) = s
astNodeSpan (ClassDeclarationNode s _) = s
astNodeSpan (ClassExpressionNode s _) = s
astNodeSpan (ConditionalExpressionNode s _) = s
astNodeSpan (ContinueStatementNode s _) = s
astNodeSpan (DebuggerStatementNode s _) = s
astNodeSpan (DecoratorNode s _) = s
astNodeSpan (DoWhileStatementNode s _) = s
astNodeSpan (EmptyStatementNode s _) = s
astNodeSpan (ExportAllDeclarationNode s _) = s
astNodeSpan (ExportDefaultDeclarationNode s _) = s
astNodeSpan (ExportNamedDeclarationNode s _) = s
astNodeSpan (ExportSpecifierNode s _) = s
astNodeSpan (ExpressionStatementNode s _) = s
astNodeSpan (ForInStatementNode s _) = s
astNodeSpan (ForOfStatementNode s _) = s
astNodeSpan (ForStatementNode s _) = s
astNodeSpan (FunctionDeclarationNode s _) = s
astNodeSpan (FunctionExpressionNode s _) = s
astNodeSpan (HashbangNode s _) = s
astNodeSpan (IdentifierNode s _) = s
astNodeSpan (IfStatementNode s _) = s
astNodeSpan (ImportAttributeNode s _) = s
astNodeSpan (ImportDeclarationNode s _) = s
astNodeSpan (ImportDefaultSpecifierNode s _) = s
astNodeSpan (ImportExpressionNode s _) = s
astNodeSpan (ImportNamespaceSpecifierNode s _) = s
astNodeSpan (ImportSpecifierNode s _) = s
astNodeSpan (JSXAttributeNode s _) = s
astNodeSpan (JSXClosingElementNode s _) = s
astNodeSpan (JSXClosingFragmentNode s _) = s
astNodeSpan (JSXElementNode s _) = s
astNodeSpan (JSXEmptyExpressionNode s _) = s
astNodeSpan (JSXExpressionContainerNode s _) = s
astNodeSpan (JSXFragmentNode s _) = s
astNodeSpan (JSXIdentifierNode s _) = s
astNodeSpan (JSXMemberExpressionNode s _) = s
astNodeSpan (JSXNamespacedNameNode s _) = s
astNodeSpan (JSXOpeningElementNode s _) = s
astNodeSpan (JSXOpeningFragmentNode s _) = s
astNodeSpan (JSXSpreadAttributeNode s _) = s
astNodeSpan (JSXSpreadChildNode s _) = s
astNodeSpan (JSXTextNode s _) = s
astNodeSpan (LabeledStatementNode s _) = s
astNodeSpan (LiteralNode s _) = s
astNodeSpan (LogicalExpressionNode s _) = s
astNodeSpan (MemberExpressionNode s _) = s
astNodeSpan (MetaPropertyNode s _) = s
astNodeSpan (MethodDefinitionNode s _) = s
astNodeSpan (NewExpressionNode s _) = s
astNodeSpan (ObjectExpressionNode s _) = s
astNodeSpan (ObjectPatternNode s _) = s
astNodeSpan (ParenthesizedExpressionNode s _) = s
astNodeSpan (PrivateIdentifierNode s _) = s
astNodeSpan (ProgramNode s _) = s
astNodeSpan (PropertyNode s _) = s
astNodeSpan (PropertyDefinitionNode s _) = s
astNodeSpan (RestElementNode s _) = s
astNodeSpan (ReturnStatementNode s _) = s
astNodeSpan (SequenceExpressionNode s _) = s
astNodeSpan (SpreadElementNode s _) = s
astNodeSpan (StaticBlockNode s _) = s
astNodeSpan (SuperNode s _) = s
astNodeSpan (SwitchCaseNode s _) = s
astNodeSpan (SwitchStatementNode s _) = s
astNodeSpan (TSAbstractAccessorPropertyNode s _) = s
astNodeSpan (TSAbstractMethodDefinitionNode s _) = s
astNodeSpan (TSAbstractPropertyDefinitionNode s _) = s
astNodeSpan (TSAnyKeywordNode s _) = s
astNodeSpan (TSArrayTypeNode s _) = s
astNodeSpan (TSAsExpressionNode s _) = s
astNodeSpan (TSBigIntKeywordNode s _) = s
astNodeSpan (TSBooleanKeywordNode s _) = s
astNodeSpan (TSCallSignatureDeclarationNode s _) = s
astNodeSpan (TSClassImplementsNode s _) = s
astNodeSpan (TSConditionalTypeNode s _) = s
astNodeSpan (TSConstructSignatureDeclarationNode s _) = s
astNodeSpan (TSConstructorTypeNode s _) = s
astNodeSpan (TSDeclareFunctionNode s _) = s
astNodeSpan (TSEmptyBodyFunctionExpressionNode s _) = s
astNodeSpan (TSEnumBodyNode s _) = s
astNodeSpan (TSEnumDeclarationNode s _) = s
astNodeSpan (TSEnumMemberNode s _) = s
astNodeSpan (TSExportAssignmentNode s _) = s
astNodeSpan (TSExternalModuleReferenceNode s _) = s
astNodeSpan (TSFunctionTypeNode s _) = s
astNodeSpan (TSImportEqualsDeclarationNode s _) = s
astNodeSpan (TSImportTypeNode s _) = s
astNodeSpan (TSIndexSignatureNode s _) = s
astNodeSpan (TSIndexedAccessTypeNode s _) = s
astNodeSpan (TSInferTypeNode s _) = s
astNodeSpan (TSInstantiationExpressionNode s _) = s
astNodeSpan (TSInterfaceBodyNode s _) = s
astNodeSpan (TSInterfaceDeclarationNode s _) = s
astNodeSpan (TSInterfaceHeritageNode s _) = s
astNodeSpan (TSIntersectionTypeNode s _) = s
astNodeSpan (TSIntrinsicKeywordNode s _) = s
astNodeSpan (TSJSDocNonNullableTypeNode s _) = s
astNodeSpan (TSJSDocNullableTypeNode s _) = s
astNodeSpan (TSJSDocUnknownTypeNode s _) = s
astNodeSpan (TSLiteralTypeNode s _) = s
astNodeSpan (TSMappedTypeNode s _) = s
astNodeSpan (TSMethodSignatureNode s _) = s
astNodeSpan (TSModuleBlockNode s _) = s
astNodeSpan (TSModuleDeclarationNode s _) = s
astNodeSpan (TSNamedTupleMemberNode s _) = s
astNodeSpan (TSNamespaceExportDeclarationNode s _) = s
astNodeSpan (TSNeverKeywordNode s _) = s
astNodeSpan (TSNonNullExpressionNode s _) = s
astNodeSpan (TSNullKeywordNode s _) = s
astNodeSpan (TSNumberKeywordNode s _) = s
astNodeSpan (TSObjectKeywordNode s _) = s
astNodeSpan (TSOptionalTypeNode s _) = s
astNodeSpan (TSParameterPropertyNode s _) = s
astNodeSpan (TSParenthesizedTypeNode s _) = s
astNodeSpan (TSPropertySignatureNode s _) = s
astNodeSpan (TSQualifiedNameNode s _) = s
astNodeSpan (TSRestTypeNode s _) = s
astNodeSpan (TSSatisfiesExpressionNode s _) = s
astNodeSpan (TSStringKeywordNode s _) = s
astNodeSpan (TSSymbolKeywordNode s _) = s
astNodeSpan (TSTemplateLiteralTypeNode s _) = s
astNodeSpan (TSThisTypeNode s _) = s
astNodeSpan (TSTupleTypeNode s _) = s
astNodeSpan (TSTypeAliasDeclarationNode s _) = s
astNodeSpan (TSTypeAnnotationNode s _) = s
astNodeSpan (TSTypeAssertionNode s _) = s
astNodeSpan (TSTypeLiteralNode s _) = s
astNodeSpan (TSTypeOperatorNode s _) = s
astNodeSpan (TSTypeParameterNode s _) = s
astNodeSpan (TSTypeParameterDeclarationNode s _) = s
astNodeSpan (TSTypeParameterInstantiationNode s _) = s
astNodeSpan (TSTypePredicateNode s _) = s
astNodeSpan (TSTypeQueryNode s _) = s
astNodeSpan (TSTypeReferenceNode s _) = s
astNodeSpan (TSUndefinedKeywordNode s _) = s
astNodeSpan (TSUnionTypeNode s _) = s
astNodeSpan (TSUnknownKeywordNode s _) = s
astNodeSpan (TSVoidKeywordNode s _) = s
astNodeSpan (TaggedTemplateExpressionNode s _) = s
astNodeSpan (TemplateElementNode s _) = s
astNodeSpan (TemplateLiteralNode s _) = s
astNodeSpan (ThisExpressionNode s _) = s
astNodeSpan (ThrowStatementNode s _) = s
astNodeSpan (TryStatementNode s _) = s
astNodeSpan (UnaryExpressionNode s _) = s
astNodeSpan (UpdateExpressionNode s _) = s
astNodeSpan (V8IntrinsicExpressionNode s _) = s
astNodeSpan (VariableDeclarationNode s _) = s
astNodeSpan (VariableDeclaratorNode s _) = s
astNodeSpan (WhileStatementNode s _) = s
astNodeSpan (WithStatementNode s _) = s
astNodeSpan (YieldExpressionNode s _) = s
astNodeSpan (UnknownNode _ s _) = s

-- | Extract the raw JSON Object from a node.
astNodeFields :: ASTNode -> Object
astNodeFields (AccessorPropertyNode _ o) = o
astNodeFields (ArrayExpressionNode _ o) = o
astNodeFields (ArrayPatternNode _ o) = o
astNodeFields (ArrowFunctionExpressionNode _ o) = o
astNodeFields (AssignmentExpressionNode _ o) = o
astNodeFields (AssignmentPatternNode _ o) = o
astNodeFields (AwaitExpressionNode _ o) = o
astNodeFields (BinaryExpressionNode _ o) = o
astNodeFields (BlockStatementNode _ o) = o
astNodeFields (BreakStatementNode _ o) = o
astNodeFields (CallExpressionNode _ o) = o
astNodeFields (CatchClauseNode _ o) = o
astNodeFields (ChainExpressionNode _ o) = o
astNodeFields (ClassBodyNode _ o) = o
astNodeFields (ClassDeclarationNode _ o) = o
astNodeFields (ClassExpressionNode _ o) = o
astNodeFields (ConditionalExpressionNode _ o) = o
astNodeFields (ContinueStatementNode _ o) = o
astNodeFields (DebuggerStatementNode _ o) = o
astNodeFields (DecoratorNode _ o) = o
astNodeFields (DoWhileStatementNode _ o) = o
astNodeFields (EmptyStatementNode _ o) = o
astNodeFields (ExportAllDeclarationNode _ o) = o
astNodeFields (ExportDefaultDeclarationNode _ o) = o
astNodeFields (ExportNamedDeclarationNode _ o) = o
astNodeFields (ExportSpecifierNode _ o) = o
astNodeFields (ExpressionStatementNode _ o) = o
astNodeFields (ForInStatementNode _ o) = o
astNodeFields (ForOfStatementNode _ o) = o
astNodeFields (ForStatementNode _ o) = o
astNodeFields (FunctionDeclarationNode _ o) = o
astNodeFields (FunctionExpressionNode _ o) = o
astNodeFields (HashbangNode _ o) = o
astNodeFields (IdentifierNode _ o) = o
astNodeFields (IfStatementNode _ o) = o
astNodeFields (ImportAttributeNode _ o) = o
astNodeFields (ImportDeclarationNode _ o) = o
astNodeFields (ImportDefaultSpecifierNode _ o) = o
astNodeFields (ImportExpressionNode _ o) = o
astNodeFields (ImportNamespaceSpecifierNode _ o) = o
astNodeFields (ImportSpecifierNode _ o) = o
astNodeFields (JSXAttributeNode _ o) = o
astNodeFields (JSXClosingElementNode _ o) = o
astNodeFields (JSXClosingFragmentNode _ o) = o
astNodeFields (JSXElementNode _ o) = o
astNodeFields (JSXEmptyExpressionNode _ o) = o
astNodeFields (JSXExpressionContainerNode _ o) = o
astNodeFields (JSXFragmentNode _ o) = o
astNodeFields (JSXIdentifierNode _ o) = o
astNodeFields (JSXMemberExpressionNode _ o) = o
astNodeFields (JSXNamespacedNameNode _ o) = o
astNodeFields (JSXOpeningElementNode _ o) = o
astNodeFields (JSXOpeningFragmentNode _ o) = o
astNodeFields (JSXSpreadAttributeNode _ o) = o
astNodeFields (JSXSpreadChildNode _ o) = o
astNodeFields (JSXTextNode _ o) = o
astNodeFields (LabeledStatementNode _ o) = o
astNodeFields (LiteralNode _ o) = o
astNodeFields (LogicalExpressionNode _ o) = o
astNodeFields (MemberExpressionNode _ o) = o
astNodeFields (MetaPropertyNode _ o) = o
astNodeFields (MethodDefinitionNode _ o) = o
astNodeFields (NewExpressionNode _ o) = o
astNodeFields (ObjectExpressionNode _ o) = o
astNodeFields (ObjectPatternNode _ o) = o
astNodeFields (ParenthesizedExpressionNode _ o) = o
astNodeFields (PrivateIdentifierNode _ o) = o
astNodeFields (ProgramNode _ o) = o
astNodeFields (PropertyNode _ o) = o
astNodeFields (PropertyDefinitionNode _ o) = o
astNodeFields (RestElementNode _ o) = o
astNodeFields (ReturnStatementNode _ o) = o
astNodeFields (SequenceExpressionNode _ o) = o
astNodeFields (SpreadElementNode _ o) = o
astNodeFields (StaticBlockNode _ o) = o
astNodeFields (SuperNode _ o) = o
astNodeFields (SwitchCaseNode _ o) = o
astNodeFields (SwitchStatementNode _ o) = o
astNodeFields (TSAbstractAccessorPropertyNode _ o) = o
astNodeFields (TSAbstractMethodDefinitionNode _ o) = o
astNodeFields (TSAbstractPropertyDefinitionNode _ o) = o
astNodeFields (TSAnyKeywordNode _ o) = o
astNodeFields (TSArrayTypeNode _ o) = o
astNodeFields (TSAsExpressionNode _ o) = o
astNodeFields (TSBigIntKeywordNode _ o) = o
astNodeFields (TSBooleanKeywordNode _ o) = o
astNodeFields (TSCallSignatureDeclarationNode _ o) = o
astNodeFields (TSClassImplementsNode _ o) = o
astNodeFields (TSConditionalTypeNode _ o) = o
astNodeFields (TSConstructSignatureDeclarationNode _ o) = o
astNodeFields (TSConstructorTypeNode _ o) = o
astNodeFields (TSDeclareFunctionNode _ o) = o
astNodeFields (TSEmptyBodyFunctionExpressionNode _ o) = o
astNodeFields (TSEnumBodyNode _ o) = o
astNodeFields (TSEnumDeclarationNode _ o) = o
astNodeFields (TSEnumMemberNode _ o) = o
astNodeFields (TSExportAssignmentNode _ o) = o
astNodeFields (TSExternalModuleReferenceNode _ o) = o
astNodeFields (TSFunctionTypeNode _ o) = o
astNodeFields (TSImportEqualsDeclarationNode _ o) = o
astNodeFields (TSImportTypeNode _ o) = o
astNodeFields (TSIndexSignatureNode _ o) = o
astNodeFields (TSIndexedAccessTypeNode _ o) = o
astNodeFields (TSInferTypeNode _ o) = o
astNodeFields (TSInstantiationExpressionNode _ o) = o
astNodeFields (TSInterfaceBodyNode _ o) = o
astNodeFields (TSInterfaceDeclarationNode _ o) = o
astNodeFields (TSInterfaceHeritageNode _ o) = o
astNodeFields (TSIntersectionTypeNode _ o) = o
astNodeFields (TSIntrinsicKeywordNode _ o) = o
astNodeFields (TSJSDocNonNullableTypeNode _ o) = o
astNodeFields (TSJSDocNullableTypeNode _ o) = o
astNodeFields (TSJSDocUnknownTypeNode _ o) = o
astNodeFields (TSLiteralTypeNode _ o) = o
astNodeFields (TSMappedTypeNode _ o) = o
astNodeFields (TSMethodSignatureNode _ o) = o
astNodeFields (TSModuleBlockNode _ o) = o
astNodeFields (TSModuleDeclarationNode _ o) = o
astNodeFields (TSNamedTupleMemberNode _ o) = o
astNodeFields (TSNamespaceExportDeclarationNode _ o) = o
astNodeFields (TSNeverKeywordNode _ o) = o
astNodeFields (TSNonNullExpressionNode _ o) = o
astNodeFields (TSNullKeywordNode _ o) = o
astNodeFields (TSNumberKeywordNode _ o) = o
astNodeFields (TSObjectKeywordNode _ o) = o
astNodeFields (TSOptionalTypeNode _ o) = o
astNodeFields (TSParameterPropertyNode _ o) = o
astNodeFields (TSParenthesizedTypeNode _ o) = o
astNodeFields (TSPropertySignatureNode _ o) = o
astNodeFields (TSQualifiedNameNode _ o) = o
astNodeFields (TSRestTypeNode _ o) = o
astNodeFields (TSSatisfiesExpressionNode _ o) = o
astNodeFields (TSStringKeywordNode _ o) = o
astNodeFields (TSSymbolKeywordNode _ o) = o
astNodeFields (TSTemplateLiteralTypeNode _ o) = o
astNodeFields (TSThisTypeNode _ o) = o
astNodeFields (TSTupleTypeNode _ o) = o
astNodeFields (TSTypeAliasDeclarationNode _ o) = o
astNodeFields (TSTypeAnnotationNode _ o) = o
astNodeFields (TSTypeAssertionNode _ o) = o
astNodeFields (TSTypeLiteralNode _ o) = o
astNodeFields (TSTypeOperatorNode _ o) = o
astNodeFields (TSTypeParameterNode _ o) = o
astNodeFields (TSTypeParameterDeclarationNode _ o) = o
astNodeFields (TSTypeParameterInstantiationNode _ o) = o
astNodeFields (TSTypePredicateNode _ o) = o
astNodeFields (TSTypeQueryNode _ o) = o
astNodeFields (TSTypeReferenceNode _ o) = o
astNodeFields (TSUndefinedKeywordNode _ o) = o
astNodeFields (TSUnionTypeNode _ o) = o
astNodeFields (TSUnknownKeywordNode _ o) = o
astNodeFields (TSVoidKeywordNode _ o) = o
astNodeFields (TaggedTemplateExpressionNode _ o) = o
astNodeFields (TemplateElementNode _ o) = o
astNodeFields (TemplateLiteralNode _ o) = o
astNodeFields (ThisExpressionNode _ o) = o
astNodeFields (ThrowStatementNode _ o) = o
astNodeFields (TryStatementNode _ o) = o
astNodeFields (UnaryExpressionNode _ o) = o
astNodeFields (UpdateExpressionNode _ o) = o
astNodeFields (V8IntrinsicExpressionNode _ o) = o
astNodeFields (VariableDeclarationNode _ o) = o
astNodeFields (VariableDeclaratorNode _ o) = o
astNodeFields (WhileStatementNode _ o) = o
astNodeFields (WithStatementNode _ o) = o
astNodeFields (YieldExpressionNode _ o) = o
astNodeFields (UnknownNode _ _ o) = o

-- | Get a typed field from the raw Object. Returns Nothing on missing/wrong type.
getField :: FromJSON a => Text -> ASTNode -> Maybe a
getField key node =
  let obj = astNodeFields node
  in case KM.lookup (K.fromText key) obj of
       Nothing -> Nothing
       Just v  -> parseMaybe parseJSON v

-- | Get a field that may be null.
getFieldMaybe :: FromJSON a => Text -> ASTNode -> Maybe (Maybe a)
getFieldMaybe key node =
  let obj = astNodeFields node
  in case KM.lookup (K.fromText key) obj of
       Nothing   -> Nothing
       Just Null -> Just Nothing
       Just v    -> Just <$> parseMaybe parseJSON v

-- | Get child nodes from an array field.
getChildren :: Text -> ASTNode -> [ASTNode]
getChildren key node =
  case KM.lookup (K.fromText key) (astNodeFields node) of
    Just (Array arr) ->
      [ child | v <- V.toList arr
      , Just child <- [parseMaybe parseJSON v]
      ]
    _ -> []

-- | Get child nodes from a field that can be a single node or null.
getChildrenMaybe :: Text -> ASTNode -> Maybe ASTNode
getChildrenMaybe key node =
  case KM.lookup (K.fromText key) (astNodeFields node) of
    Just Null -> Nothing
    Just v    -> parseMaybe parseJSON v
    Nothing   -> Nothing

-- | Get a text field with a default.
getTextFieldOr :: Text -> Text -> ASTNode -> Text
getTextFieldOr key def node = maybe def id (getField key node)

-- | Get a boolean field with a default.
getBoolFieldOr :: Text -> Bool -> ASTNode -> Bool
getBoolFieldOr key def node = maybe def id (getField key node)

-- ── FromJSON instance ───────────────────────────────────────────────────

instance FromJSON ASTNode where
  parseJSON = withObject "ASTNode" $ \obj -> do
    typ <- obj .: "type" :: Parser Text
    st  <- obj .: "start" :: Parser Int
    en  <- obj .: "end"   :: Parser Int
    let sp = Span st en
    case typ of
      "AccessorProperty" -> pure (AccessorPropertyNode sp obj)
      "ArrayExpression" -> pure (ArrayExpressionNode sp obj)
      "ArrayPattern" -> pure (ArrayPatternNode sp obj)
      "ArrowFunctionExpression" -> pure (ArrowFunctionExpressionNode sp obj)
      "AssignmentExpression" -> pure (AssignmentExpressionNode sp obj)
      "AssignmentPattern" -> pure (AssignmentPatternNode sp obj)
      "AwaitExpression" -> pure (AwaitExpressionNode sp obj)
      "BinaryExpression" -> pure (BinaryExpressionNode sp obj)
      "BlockStatement" -> pure (BlockStatementNode sp obj)
      "BreakStatement" -> pure (BreakStatementNode sp obj)
      "CallExpression" -> pure (CallExpressionNode sp obj)
      "CatchClause" -> pure (CatchClauseNode sp obj)
      "ChainExpression" -> pure (ChainExpressionNode sp obj)
      "ClassBody" -> pure (ClassBodyNode sp obj)
      "ClassDeclaration" -> pure (ClassDeclarationNode sp obj)
      "ClassExpression" -> pure (ClassExpressionNode sp obj)
      "ConditionalExpression" -> pure (ConditionalExpressionNode sp obj)
      "ContinueStatement" -> pure (ContinueStatementNode sp obj)
      "DebuggerStatement" -> pure (DebuggerStatementNode sp obj)
      "Decorator" -> pure (DecoratorNode sp obj)
      "DoWhileStatement" -> pure (DoWhileStatementNode sp obj)
      "EmptyStatement" -> pure (EmptyStatementNode sp obj)
      "ExportAllDeclaration" -> pure (ExportAllDeclarationNode sp obj)
      "ExportDefaultDeclaration" -> pure (ExportDefaultDeclarationNode sp obj)
      "ExportNamedDeclaration" -> pure (ExportNamedDeclarationNode sp obj)
      "ExportSpecifier" -> pure (ExportSpecifierNode sp obj)
      "ExpressionStatement" -> pure (ExpressionStatementNode sp obj)
      "ForInStatement" -> pure (ForInStatementNode sp obj)
      "ForOfStatement" -> pure (ForOfStatementNode sp obj)
      "ForStatement" -> pure (ForStatementNode sp obj)
      "FunctionDeclaration" -> pure (FunctionDeclarationNode sp obj)
      "FunctionExpression" -> pure (FunctionExpressionNode sp obj)
      "Hashbang" -> pure (HashbangNode sp obj)
      "Identifier" -> pure (IdentifierNode sp obj)
      "IfStatement" -> pure (IfStatementNode sp obj)
      "ImportAttribute" -> pure (ImportAttributeNode sp obj)
      "ImportDeclaration" -> pure (ImportDeclarationNode sp obj)
      "ImportDefaultSpecifier" -> pure (ImportDefaultSpecifierNode sp obj)
      "ImportExpression" -> pure (ImportExpressionNode sp obj)
      "ImportNamespaceSpecifier" -> pure (ImportNamespaceSpecifierNode sp obj)
      "ImportSpecifier" -> pure (ImportSpecifierNode sp obj)
      "JSXAttribute" -> pure (JSXAttributeNode sp obj)
      "JSXClosingElement" -> pure (JSXClosingElementNode sp obj)
      "JSXClosingFragment" -> pure (JSXClosingFragmentNode sp obj)
      "JSXElement" -> pure (JSXElementNode sp obj)
      "JSXEmptyExpression" -> pure (JSXEmptyExpressionNode sp obj)
      "JSXExpressionContainer" -> pure (JSXExpressionContainerNode sp obj)
      "JSXFragment" -> pure (JSXFragmentNode sp obj)
      "JSXIdentifier" -> pure (JSXIdentifierNode sp obj)
      "JSXMemberExpression" -> pure (JSXMemberExpressionNode sp obj)
      "JSXNamespacedName" -> pure (JSXNamespacedNameNode sp obj)
      "JSXOpeningElement" -> pure (JSXOpeningElementNode sp obj)
      "JSXOpeningFragment" -> pure (JSXOpeningFragmentNode sp obj)
      "JSXSpreadAttribute" -> pure (JSXSpreadAttributeNode sp obj)
      "JSXSpreadChild" -> pure (JSXSpreadChildNode sp obj)
      "JSXText" -> pure (JSXTextNode sp obj)
      "LabeledStatement" -> pure (LabeledStatementNode sp obj)
      "Literal" -> pure (LiteralNode sp obj)
      "LogicalExpression" -> pure (LogicalExpressionNode sp obj)
      "MemberExpression" -> pure (MemberExpressionNode sp obj)
      "MetaProperty" -> pure (MetaPropertyNode sp obj)
      "MethodDefinition" -> pure (MethodDefinitionNode sp obj)
      "NewExpression" -> pure (NewExpressionNode sp obj)
      "ObjectExpression" -> pure (ObjectExpressionNode sp obj)
      "ObjectPattern" -> pure (ObjectPatternNode sp obj)
      "ParenthesizedExpression" -> pure (ParenthesizedExpressionNode sp obj)
      "PrivateIdentifier" -> pure (PrivateIdentifierNode sp obj)
      "Program" -> pure (ProgramNode sp obj)
      "Property" -> pure (PropertyNode sp obj)
      "PropertyDefinition" -> pure (PropertyDefinitionNode sp obj)
      "RestElement" -> pure (RestElementNode sp obj)
      "ReturnStatement" -> pure (ReturnStatementNode sp obj)
      "SequenceExpression" -> pure (SequenceExpressionNode sp obj)
      "SpreadElement" -> pure (SpreadElementNode sp obj)
      "StaticBlock" -> pure (StaticBlockNode sp obj)
      "Super" -> pure (SuperNode sp obj)
      "SwitchCase" -> pure (SwitchCaseNode sp obj)
      "SwitchStatement" -> pure (SwitchStatementNode sp obj)
      "TSAbstractAccessorProperty" -> pure (TSAbstractAccessorPropertyNode sp obj)
      "TSAbstractMethodDefinition" -> pure (TSAbstractMethodDefinitionNode sp obj)
      "TSAbstractPropertyDefinition" -> pure (TSAbstractPropertyDefinitionNode sp obj)
      "TSAnyKeyword" -> pure (TSAnyKeywordNode sp obj)
      "TSArrayType" -> pure (TSArrayTypeNode sp obj)
      "TSAsExpression" -> pure (TSAsExpressionNode sp obj)
      "TSBigIntKeyword" -> pure (TSBigIntKeywordNode sp obj)
      "TSBooleanKeyword" -> pure (TSBooleanKeywordNode sp obj)
      "TSCallSignatureDeclaration" -> pure (TSCallSignatureDeclarationNode sp obj)
      "TSClassImplements" -> pure (TSClassImplementsNode sp obj)
      "TSConditionalType" -> pure (TSConditionalTypeNode sp obj)
      "TSConstructSignatureDeclaration" -> pure (TSConstructSignatureDeclarationNode sp obj)
      "TSConstructorType" -> pure (TSConstructorTypeNode sp obj)
      "TSDeclareFunction" -> pure (TSDeclareFunctionNode sp obj)
      "TSEmptyBodyFunctionExpression" -> pure (TSEmptyBodyFunctionExpressionNode sp obj)
      "TSEnumBody" -> pure (TSEnumBodyNode sp obj)
      "TSEnumDeclaration" -> pure (TSEnumDeclarationNode sp obj)
      "TSEnumMember" -> pure (TSEnumMemberNode sp obj)
      "TSExportAssignment" -> pure (TSExportAssignmentNode sp obj)
      "TSExternalModuleReference" -> pure (TSExternalModuleReferenceNode sp obj)
      "TSFunctionType" -> pure (TSFunctionTypeNode sp obj)
      "TSImportEqualsDeclaration" -> pure (TSImportEqualsDeclarationNode sp obj)
      "TSImportType" -> pure (TSImportTypeNode sp obj)
      "TSIndexSignature" -> pure (TSIndexSignatureNode sp obj)
      "TSIndexedAccessType" -> pure (TSIndexedAccessTypeNode sp obj)
      "TSInferType" -> pure (TSInferTypeNode sp obj)
      "TSInstantiationExpression" -> pure (TSInstantiationExpressionNode sp obj)
      "TSInterfaceBody" -> pure (TSInterfaceBodyNode sp obj)
      "TSInterfaceDeclaration" -> pure (TSInterfaceDeclarationNode sp obj)
      "TSInterfaceHeritage" -> pure (TSInterfaceHeritageNode sp obj)
      "TSIntersectionType" -> pure (TSIntersectionTypeNode sp obj)
      "TSIntrinsicKeyword" -> pure (TSIntrinsicKeywordNode sp obj)
      "TSJSDocNonNullableType" -> pure (TSJSDocNonNullableTypeNode sp obj)
      "TSJSDocNullableType" -> pure (TSJSDocNullableTypeNode sp obj)
      "TSJSDocUnknownType" -> pure (TSJSDocUnknownTypeNode sp obj)
      "TSLiteralType" -> pure (TSLiteralTypeNode sp obj)
      "TSMappedType" -> pure (TSMappedTypeNode sp obj)
      "TSMethodSignature" -> pure (TSMethodSignatureNode sp obj)
      "TSModuleBlock" -> pure (TSModuleBlockNode sp obj)
      "TSModuleDeclaration" -> pure (TSModuleDeclarationNode sp obj)
      "TSNamedTupleMember" -> pure (TSNamedTupleMemberNode sp obj)
      "TSNamespaceExportDeclaration" -> pure (TSNamespaceExportDeclarationNode sp obj)
      "TSNeverKeyword" -> pure (TSNeverKeywordNode sp obj)
      "TSNonNullExpression" -> pure (TSNonNullExpressionNode sp obj)
      "TSNullKeyword" -> pure (TSNullKeywordNode sp obj)
      "TSNumberKeyword" -> pure (TSNumberKeywordNode sp obj)
      "TSObjectKeyword" -> pure (TSObjectKeywordNode sp obj)
      "TSOptionalType" -> pure (TSOptionalTypeNode sp obj)
      "TSParameterProperty" -> pure (TSParameterPropertyNode sp obj)
      "TSParenthesizedType" -> pure (TSParenthesizedTypeNode sp obj)
      "TSPropertySignature" -> pure (TSPropertySignatureNode sp obj)
      "TSQualifiedName" -> pure (TSQualifiedNameNode sp obj)
      "TSRestType" -> pure (TSRestTypeNode sp obj)
      "TSSatisfiesExpression" -> pure (TSSatisfiesExpressionNode sp obj)
      "TSStringKeyword" -> pure (TSStringKeywordNode sp obj)
      "TSSymbolKeyword" -> pure (TSSymbolKeywordNode sp obj)
      "TSTemplateLiteralType" -> pure (TSTemplateLiteralTypeNode sp obj)
      "TSThisType" -> pure (TSThisTypeNode sp obj)
      "TSTupleType" -> pure (TSTupleTypeNode sp obj)
      "TSTypeAliasDeclaration" -> pure (TSTypeAliasDeclarationNode sp obj)
      "TSTypeAnnotation" -> pure (TSTypeAnnotationNode sp obj)
      "TSTypeAssertion" -> pure (TSTypeAssertionNode sp obj)
      "TSTypeLiteral" -> pure (TSTypeLiteralNode sp obj)
      "TSTypeOperator" -> pure (TSTypeOperatorNode sp obj)
      "TSTypeParameter" -> pure (TSTypeParameterNode sp obj)
      "TSTypeParameterDeclaration" -> pure (TSTypeParameterDeclarationNode sp obj)
      "TSTypeParameterInstantiation" -> pure (TSTypeParameterInstantiationNode sp obj)
      "TSTypePredicate" -> pure (TSTypePredicateNode sp obj)
      "TSTypeQuery" -> pure (TSTypeQueryNode sp obj)
      "TSTypeReference" -> pure (TSTypeReferenceNode sp obj)
      "TSUndefinedKeyword" -> pure (TSUndefinedKeywordNode sp obj)
      "TSUnionType" -> pure (TSUnionTypeNode sp obj)
      "TSUnknownKeyword" -> pure (TSUnknownKeywordNode sp obj)
      "TSVoidKeyword" -> pure (TSVoidKeywordNode sp obj)
      "TaggedTemplateExpression" -> pure (TaggedTemplateExpressionNode sp obj)
      "TemplateElement" -> pure (TemplateElementNode sp obj)
      "TemplateLiteral" -> pure (TemplateLiteralNode sp obj)
      "ThisExpression" -> pure (ThisExpressionNode sp obj)
      "ThrowStatement" -> pure (ThrowStatementNode sp obj)
      "TryStatement" -> pure (TryStatementNode sp obj)
      "UnaryExpression" -> pure (UnaryExpressionNode sp obj)
      "UpdateExpression" -> pure (UpdateExpressionNode sp obj)
      "V8IntrinsicExpression" -> pure (V8IntrinsicExpressionNode sp obj)
      "VariableDeclaration" -> pure (VariableDeclarationNode sp obj)
      "VariableDeclarator" -> pure (VariableDeclaratorNode sp obj)
      "WhileStatement" -> pure (WhileStatementNode sp obj)
      "WithStatement" -> pure (WithStatementNode sp obj)
      "YieldExpression" -> pure (YieldExpressionNode sp obj)
      other -> pure (UnknownNode other sp obj)
